#!/bin/sh

enable() {
    nft -f - <<'EOF'
destroy table inet killswitch
table inet killswitch {
    chain input {
        type filter hook input priority -300; policy accept;
        iif lo accept
        drop
    }
    chain output {
        type filter hook output priority -300; policy accept;
        oif lo accept
        drop
    }
    chain forward {
        type filter hook forward priority -300; policy accept;
        iif lo accept
        oif lo accept
        drop
    }
}
EOF
}

case "$1" in
    --status)
	:
	;;
    --on)
        enable
        ;;
    --off)
	nft destroy table inet killswitch >/dev/null 2>&1
        ;;
esac

if nft list table inet killswitch >/dev/null 2>&1; then
	printf '%s\n' "x"
else
	printf '%s\n' "✓"
fi


